config/routes.rb
Rails.application.routes.draw do
  resources :dictionaries
  root 'dictionaries#new'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dictionary.rb
# == Schema Information
#
# Table name: dictionaries
#
#  id          :bigint           not null, primary key
#  name        :string           not null
#  description :text             not null
#  fruit_id    :bigint           not null
#  pet_id      :bigint           not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#
class Dictionary < ApplicationRecord
  belongs_to :fruit
  belongs_to :pet

  # Validations
  validates :fruit_id,      presence: true
  validates :pet_id,        presence: true
  validates :name,          presence: true,
                            length: { maximum: 50 }
  validates :description,   presence: true,
                            length: { maximum: 500 }
end

app/models/fruit.rb
# == Schema Information
#
# Table name: fruits
#
#  id          :bigint           not null, primary key
#  name        :string           not null
#  description :text             not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#
class Fruit < ApplicationRecord
  # Validations
  validates :name, presence: true
  validates :description, presence: true
end

app/models/pet.rb
# == Schema Information
#
# Table name: pets
#
#  id          :bigint           not null, primary key
#  name        :string           not null
#  description :text             not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#
class Pet < ApplicationRecord
  # Validations
  validates :name, presence: true
  validates :description, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/dictionaries_controller.rb
class DictionariesController < ApplicationController
  before_action :set_dictionary, only: %i[ show edit update destroy ]

  # GET /dictionaries or /dictionaries.json
  def index
    @dictionaries = Dictionary.all
  end

  # GET /dictionaries/1 or /dictionaries/1.json
  def show
  end

  # GET /dictionaries/new
  def new
    @dictionary = Dictionary.new
  end

  # GET /dictionaries/1/edit
  def edit
  end

  # POST /dictionaries or /dictionaries.json
  def create
    @dictionary = Dictionary.new(dictionary_params)

    respond_to do |format|
      if @dictionary.save
        format.html { redirect_to @dictionary, notice: "Dictionary was successfully created." }
        format.json { render :show, status: :created, location: @dictionary }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @dictionary.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dictionaries/1 or /dictionaries/1.json
  def update
    respond_to do |format|
      if @dictionary.update(dictionary_params)
        format.html { redirect_to @dictionary, notice: "Dictionary was successfully updated." }
        format.json { render :show, status: :ok, location: @dictionary }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @dictionary.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dictionaries/1 or /dictionaries/1.json
  def destroy
    @dictionary.destroy
    respond_to do |format|
      format.html { redirect_to dictionaries_url, notice: "Dictionary was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dictionary
      @dictionary = Dictionary.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def dictionary_params
      params.require(:dictionary).permit(:name, :description, :fruit_id, :pet_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dictionaries_helper.rb
module DictionariesHelper
end

app/views/dictionaries/_form.html.erb
<%= form_with(model: dictionary) do |form| %>
  <% if dictionary.errors.any? %>
    <article id="error_explanation" class="message is-danger">
      <div class="message-header">
        <p><%= pluralize(dictionary.errors.count, "error") %> prohibited this dictionary from being saved:</p>
        <button class="delete" aria-label="delete"></button>
      </div>
      <div class="message-body">
        <ul>
        <% dictionary.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
      </div>
    </article>
  <% end %>

  <div class="field">
    <div class="control">
      <%= form.label :name, class: "label" %>
      <%= form.text_field :name,
                          autofocus: true,
                          required: true,
                          maxlength: 50,
                          placeholder: "Name",
                          class: "input" %>
    </div>
  </div>

  <div class="field">
    <%= form.label :description, class: "label" %>
    <%= form.text_area  :description,
                        required: true,
                        maxlength: 500,
                        placeholder: "Description",
                        rows: 3,
                        class: "textarea" %>
  </div>

  <div class="field is-horizontal">
    <div class="field-body">
      <div class="container">
        <div class="columns">
          <div class="column is-6">
          </div>
          <div class="column is-6">
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="field is-horizontal">
    <div class="field-body">
      <div class="container">
        <div class="columns">
          <div class="column is-6">
            <div class="field">
              <%= form.label :fruit_id, class:"label" %>
              <div class="control">
                <div class="select is-fullwidth">
                  <%= form.collection_select  :fruit_id,
                                              Fruit.all,
                                              :id,
                                              :name,
                                              required: true,
                                              include_blank:true %>
                </div>
              </div>
            </div>
          </div>
          <div class="column is-6">
            <div class="field">
              <%= form.label :pet_id, class:"label" %>
              <div class="control">
                <div class="select is-fullwidth">
                  <%= form.collection_select  :pet_id,
                                              Pet.all,
                                              :id,
                                              :name,
                                              required: true,
                                              include_blank:true %>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <hr>
  <div class="field has-text-centered">
    <%= form.submit "Send",  class: "button is-primary is-medium is-fullwidth is-rounded" %>
  </div>
<% end %>

app/views/dictionaries/edit.html.erb
<h1 class="title is-4 has-text-dark">
  Editing Dictionary
</h1>

<%= render 'form', dictionary: @dictionary %>

app/views/dictionaries/index.html.erb
<h1 class="title is-4 has-text-dark">
  Dictionaries
</h1>

<div class="field is-grouped is-grouped-right">
  <div class="control">
    <%= link_to 'New Dictionary', new_dictionary_path, class: "button is-primary is-medium is-rounded" %>
  </div>
</div>

<table class="table is-bordered is-striped is-narrow is-hoverable is-fullwidth">
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Fruit</th>
      <th>Pet</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @dictionaries.each do |dictionary| %>
      <tr>
        <td><%= truncate(dictionary.name, length: 20) %></td>
        <td><%= truncate(dictionary.description, length: 50) %></td>
        <td><%= (dictionary.fruit.name if dictionary.fruit) %></td>
        <td><%= (dictionary.pet.name if dictionary.pet) %></td>
        <td><%= link_to 'Show', dictionary %></td>
        <td><%= link_to 'Edit', edit_dictionary_path(dictionary) %></td>
        <td><%= link_to 'Destroy', dictionary, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/dictionaries/new.html.erb
<h1 class="title is-4 has-text-dark">
  New Dictionary
</h1>

<%= render 'form', dictionary: @dictionary %>

app/views/dictionaries/show.html.erb
<div class="content">
  <h1><%= @dictionary.name %></h1>
  <div class="tags are-medium">
    <span class="tag is-info"><%= (@dictionary.fruit.name if @dictionary.fruit) %></span>
    <span class="tag is-info"><%= (@dictionary.pet.name if @dictionary.pet) %></span>
  </div>
  <p><%= @dictionary.description %></p>
</div>

<div class="buttons">
  <%= link_to 'Edit', edit_dictionary_path(@dictionary), class: 'button is-fullwidth' %>
  <%= link_to 'Back', dictionaries_path, class: 'button is-fullwidth' %>
</div>

app/views/shared/_alert.html.erb
<% if flash[:notice] %>
  <div id="notice_wrapper" class="notification is-success is-light has-text-centered">
    <button class="delete"></button>
    <%= notice %>
  </div>
<% end %>
<% if flash[:alert] %>
  <div id="notice_wrapper" class="notification is-danger is-light has-text-centered">
    <button class="delete"></button>
    <%= alert %>
  </div>
<% end %>
<% if flash[:error] %>
  <div id="notice_wrapper" class="notification is-danger is-light has-text-centered">
    <button class="delete"></button>
    <%= flash[:error] %>
  </div>
<% end %>